// Generated by CoffeeScript 1.7.1
(function() {
  var $, fill;

  $ = require('jquery');

  (fill = function(item) {
    return $('.tagline').append("" + item);
  })('The most creative minds in Art');

  fill;

}).call(this);
